### ISSUE TITLE
Technology sounds should be excluded

### ISSUE THREAD

**Issue by metablaster** [RobLoach/Civ-IV-Audio#2]
First of all thank you for mod!

Technology sounds should be excluded because text of technologies is different than what sounds say so they should not be present.

To reproduce, research a technology and you'll see text says one thing but the sound says something else.

**Comment by RobLoach** [comment]
What Leonard Nimoy says is different than the text you see on the screen because it's audio from Civ 4. This is intended to be used with the Civ IV mod, but can be used with Unciv Vanilla.

Do you believe we should split this mod into two? One for Sounds, and one for Music?

**Comment by metablaster** [comment]
> Do you believe we should split this mod into two? One for Sounds, and one for Music?

I see now... I have 4 music mods, this one and, [Civ 3 Audio](https://github.com/RobLoach/Civ-3-Audio), [Civilization 2 Music](https://github.com/Caballero-Arepa/Victoria-II-Music) and [Victoria II Music](https://github.com/Caballero-Arepa/Victoria-II-Music)

Music is not a problem for having this mix because music is played sequentially so it all works, but for sounds I'm not sure which mod takes precedence but I'll test this. do you have any idea which sounds (not music) takes effect if multiple mods are enabled?

In case case problem with this mod is only music for "Technology - Researched" music, so splitting sounds from music won't fix it.
Instead I suggest like you said a separate mod that would exclude only "Technology - Researched" music because it's the only problem for Vanilla Unciv.

Is this possible? I would be grateful to you :)

**Comment by RobLoach** [comment]
> [Civ 3 Audio](https://github.com/RobLoach/Civ-3-Audio)

Just renamed that to "Civ 3 Music", and removed those associated sounds. That seems appropriate.

> do you have any idea which sounds (not music) takes effect if multiple mods are enabled?

I have no clue. Looking at https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/ui/audio/SoundPlayer.kt#L138 , it seems like it goes through the list of folders, and returns the first file is finds in the mod list, but I could be wrong. I'm also unclear on how the mod list is ordered.

> separate mod that would exclude only "Technology - Researched" music because it's the only problem for Vanilla Unciv.

I think that makes sense. It'll be "Civ IV Music", and "Civ IV Sounds".

**Comment by metablaster** [comment]
Thank you my friend! patiently waiting for it :)

**Comment by RobLoach** [comment]
You'll want to Delete Civ IV Audio, and download the new Civ IV Music one. Thanks! Moved the sounds to https://github.com/RobLoach/Civ-IV-Sounds .

**Comment by metablaster** [comment]
Thank you very much for your time and effort, tested, it works fine!
Closing this since it's solved.
